# Generated by Django 5.2.6 on 2025-09-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('artists', models.TextField()),
                ('album_cover_url', models.URLField(max_length=500, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'spotify_track_id', 'period', 'rank')},
            },
        ),
    ]
